/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.caiodorn.nand2tetris.assembly

import spock.lang.Specification

class HackAssemblerTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new HackAssembler()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
