/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.caiodorn.nand2tetris.assembly;

public class HackAssembler {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new HackAssembler().getGreeting());
    }
}
